### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by wholmgren** [AssessingSolar/solar_multiplot#1]
Hi @AdamRJensen! I am thinking about using/adapting/possibly contributing to this code. But it needs a license before I can even consider it. Are you able to add a license?

**Comment by AdamRJensen** [comment]
Hi @wholmgren

A license has been added. It'd be great with some feedback on it (is matplotlib even the most optimal?)!

I know that @YvesMSaintDrenan has made a better/newer version. @YvesMSaintDrenan is your updated version available somewhere?

**Comment by wholmgren** [comment]
Thanks @AdamRJensen! We will try it out and provide feedback.

**Comment by YvesMSaintDrenan** [comment]
Hi @AdamRJensen and @wholmgren!

indeed we have an update version of the codes. You can find it on the following link:

https://git.sophia.mines-paristech.fr/oie/libinsitu/-/blob/main/example-notebook.ipynb

**Comment by AdamRJensen** [comment]
@wholmgren did you get a chance to use it?

**Comment by wholmgren** [comment]
@AdamRJensen not yet, but I think I'll have a project in the next few weeks that this will be well-suited for.
